name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Run Unit Tests

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
         sudo apt-get update
         sudo apt-get install -y \
           libgtk-3-dev \
           libwebkit2gtk-4.0-dev \
           build-essential \
           curl \
           libssl-dev \
           libudev-dev \
           libappindicator3-dev \
           librsvg2-dev

      - name: Run tests
        run: cd src-tauri && cargo test --verbose
